<a href="https://colab.research.google.com/github/Bugaro-Angelina/TOD-PI22-3/blob/main/1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Семинар №1
## __Дата:__ 08.02.2023     
__Выполнил:__ Бугаро Ангелина    
__Группа:__ ПИ22-3

Файл minutes_n_ingredients.csv содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов.
1. Считайте данные из этого файла в виде массива numpy типа int32, используя np.load_txt. Выведите на экран первые 5 строк массива.

In [7]:
import numpy as np 
 
dataset = np.loadtxt(r"minutes_n_ingredients.csv", delimiter=",", skiprows=1, dtype=np.int32) 
dataset[:5] 

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [8]:
print(dataset[:, 1:].mean(axis=0), 
      dataset[:, 1:].min(axis=0), 
      dataset[:, 1:].max(axis=0), 
      np.median(dataset[:, 1:], axis=0), sep="\n") 

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля  q0.75 .

In [9]:
q075 = np.quantile(dataset[:, 1], 0.75)
dataset[:, 1].clip(max=q075, out=dataset[:, 1])

array([60, 25, 10, ..., 65,  5, 65], dtype=int32)


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [10]:
print(len(dataset[:,1]) - np.count_nonzero(dataset[:,1])) 
dataset[:,1][dataset[:,1] == 0 ] = 1
dataset[409:413,1]

479


array([30, 65,  1, 45], dtype=int32)

5. Посчитайте, сколько уникальных рецептов находится в датасете.


In [11]:
np.unique(dataset[:, 0]).shape[0]

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?


In [12]:
arr = np.unique(dataset[:,2])
print(np.size(arr),arr)

37 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [13]:
recipes5 = dataset[dataset[:, 2] <= 5]
recipes5

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]], dtype=int32)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [14]:
v = np.divide(dataset[:,2], dataset[:,1])
print(v,'\nМаксимальное значение:',v.max(axis=0))

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.21538462] 
Максимальное значение: 24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [15]:
dataset[dataset[:, 1].argsort()][:, 2][-100:].mean()

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [16]:
dataset[np.random.randint(dataset.shape[0], size=10)]

array([[ 74516,     65,     12],
       [118499,     65,     12],
       [ 53402,     65,     15],
       [ 27451,     25,     17],
       [196104,     65,      6],
       [167467,     40,      8],
       [ 70942,     50,     10],
       [367226,     30,      7],
       [154896,     65,      4],
       [472994,     65,     14]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [17]:
np.where(dataset[:, 2] < dataset[:, 2].mean())[0].shape[0] / dataset.shape[0] * 100

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [22]:
new_recipe = np.append(recipe, np.zeros((recipe.shape[0],1), dtype = 'int32'), axis = 1)
new_recipe[np.logical_and(new_recipe[:,1]<=20,new_recipe[:,2]<=5)] = 1
new_recipe = new_recipe.copy()
print(new_recipe)

[[127244     60     16      0      0]
 [ 23891     25      7      0      0]
 [ 94746     10      6      0      0]
 ...
 [498432     65     15      0      0]
 [     1      1      1      1      1]
 [ 81993     65     14      0      0]]


13. Выведите процент "простых" рецептов в датасете

In [23]:
print((100*len(new_recipe[new_recipe[:,3] == 1]))/len(recipe))

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [20]:
rshort = dataset[dataset[:, 1] < 10]
rnormal = dataset[(dataset[:, 1] > 10) & (dataset[:, 1] < 20)]
rlong = dataset[dataset[:, 1] >= 20]

maximum = min([rshort.shape[0], rnormal.shape[0], rlong.shape[0]])
np.array([rshort[:maximum], rnormal[:maximum], rlong[:maximum]])

array([[[ 67660,      5,      6],
        [366174,      7,      9],
        [204134,      5,      3],
        ...,
        [420725,      5,      3],
        [  4747,      1,      9],
        [370915,      5,      4]],

       [[ 33941,     18,      9],
        [446597,     15,      5],
        [ 81006,     12,      7],
        ...,
        [278297,     12,      7],
        [ 66970,     15,      8],
        [ 90921,     18,      8]],

       [[127244,     60,     16],
        [ 23891,     25,      7],
        [157911,     60,     14],
        ...,
        [168901,     25,      7],
        [392339,     35,     13],
        [206732,     45,     10]]], dtype=int32)